##### 1.Sayılardan oluşan bir boyutlu array oluşturun. Arrayi oluştururken sayıların veri tipini integer olarak belirtelim.

Oluşturulan arrayin boyut, eleman sayısı bilgilerine bakalım.

In [6]:
import numpy as np
dizi=np.array([5,8,12,46,9,4.5],dtype="int")
print(dizi.ndim)
print(dizi.dtype)
print(dizi.size)

1
int32
6


##### 2. Aşağıda verilen iki boyutlu ve üç boyutlu arrayi oluşturalım. Bu arraylerin boyut, eleman sayısı, satır, sütun bilgilerine ulaşalım. 

İki boyutlu array:
[[1,2,6,7],
 [4,3,9,5]]

Üç boyutlu array:
[[[7,5,14],[21,8,11]],
 [[8,6,20],[14,3,9]]]

 

In [10]:
array1=np.array([[1,2,6,7],[4,3,9,5]])
array2=np.array([[[7,5,14],[21,8,11]],[[8,6,20],[14,3,9]]])
print(array1)
print(array2)
print(array1.size)   #eleman sayısı
print(array2.size)
print(array1.ndim)   #boyut
print(array2.ndim)
print(np.shape(array1)) #satır,sütun
print(np.shape(array2))

[[1 2 6 7]
 [4 3 9 5]]
[[[ 7  5 14]
  [21  8 11]]

 [[ 8  6 20]
  [14  3  9]]]
8
12
2
3
(2, 4)
(2, 2, 3)


##### 3. İstenilen elamanlara ulaşmak için arrayler üzerinde indexleme işlemi yapalım

In [15]:
#İki boyutlu arraydaki 2 elemanına ulaşalım
print(array1)
array1[0,1]

[[1 2 6 7]
 [4 3 9 5]]


2

In [16]:
#İki boyutlu arraydaki 7 elemanına ulaşalım
array1[0,-1]

7

In [18]:
#Üç boyutlu arraydaki 9 elemanına ulaşalım
print(array2)
array2[1,1,-1]

[[[ 7  5 14]
  [21  8 11]]

 [[ 8  6 20]
  [14  3  9]]]


9

In [19]:
#Üç boyutlu arraydaki 5 elemanına ulaşalım
array2[0,0,1]

5

##### 4. Arrayler üzerinde slicing işlemi uygulayalım.

In [21]:
#İki boyutlu arraydaki 2,6 elemanlarına ulaşalım
print(array1)
array1[0,1:3]

[[1 2 6 7]
 [4 3 9 5]]


array([2, 6])

In [22]:
#İki boyutlu arraydaki 3,9,5 elemanlarına ulaşalım
array1[1,1:]

array([3, 9, 5])

In [24]:
#Üç boyutlu arraydaki 21,8,11 elemanlarına ulaşalım
print(array2)
array2[0,1]

[[[ 7  5 14]
  [21  8 11]]

 [[ 8  6 20]
  [14  3  9]]]


array([21,  8, 11])

In [25]:
#Üç boyutlu arraydaki 6,20 elemanlarına ulaşalım
array2[1,0,1:]

array([ 6, 20])

##### 5. 5 satır 3 sütunluk sıfırlardan ve birlerden oluşan iki tane iki boyutlu array oluşturalım. Bu arrayleri satır ve sütun bazında birleştirelim.

In [34]:
one=np.ones((5,3),dtype="int")
zero=np.zeros((5,3),dtype="int")
print(one)
print(zero)
bir1=np.concatenate([one,zero])
bir2=np.concatenate([one,zero],axis=1)
print(bir1)
print(bir2)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1 0 0 0]
 [1 1 1 0 0 0]
 [1 1 1 0 0 0]
 [1 1 1 0 0 0]
 [1 1 1 0 0 0]]
